name: Lint Python code

on:  
    push:
        branches:
        - main

    pull_request:
        branches:
        - main

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.10"]

        steps:
        - uses: actions/checkout@v3

        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v3
          with:
              python-version: ${{ matrix.python-version }}

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install flake8 pylint

        - name: Lint code with Flake8
          run: |
            flake8                              \
                --max-line-length=120           \
                $(git ls-files "*.py")

        - name: Lint code with PyLint
          run: |
            pylint                              \
                --max-line-length=120           \
                --disable                       \
                    R0801                       \                           # Duplicate code.
                    R0903                       \                           # Too few public methods.
                    W0102                       \                           # Logging f-string interpolation.
                    W0212                       \                           # Logging f-string interpolation.
                    W1203                       \                           # Logging f-string interpolation.
                $(git ls-files "*.py")
